name: Release macOS Binary

on:
  push:
    tags:
      # Only match semantic versioning format
      # Matches v1.2.3 format
      # Excludes pre-release versions like v1.2.3-alpha.1
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  verify-tag:
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check.outputs.is_valid }}
    steps:
      - name: Check semantic version format
        id: check
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    needs: verify-tag
    if: needs.verify-tag.outputs.is_valid == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          brew install sqlite3

      - name: Build
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          COMMIT=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          mkdir -p dist
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build \
            -ldflags "-s -w \
              -X github.com/nrtkbb/fssq/cmd/version.Version=${VERSION} \
              -X github.com/nrtkbb/fssq/cmd/version.Commit=${COMMIT} \
              -X github.com/nrtkbb/fssq/cmd/version.Date=${BUILD_DATE}" \
            -tags=sqlite_foreign_keys \
            -o dist/fssq-darwin-amd64
          
          cd dist && tar czf fssq-darwin-amd64.tar.gz fssq-darwin-amd64

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/fssq-darwin-amd64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
